  File "run_all_blocks.sh", line 1
    python3 generalized_learning.py --base-dir ./outputs --config-file generalized_learning/benchmarks/blocksworld/blocks3.yaml
                               ^
SyntaxError: invalid syntax
(2022-04-01 12:37:14,098) [     INFO]: Running config, name=example
(2022-04-01 12:37:14,098) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 380.10 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed:  33%|███▎      | 1/3 [00:29<00:58, 29.20s/ chunks]Completed: 100%|██████████| 3/3 [00:40<00:00, 11.78s/ chunks]Completed: 100%|██████████| 3/3 [00:40<00:00, 13.52s/ chunks]
(2022-04-01 12:37:54,671) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 368.01 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed: 100%|██████████| 3/3 [00:00<00:00, 143.92 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[4:inf])'
(2022-04-01 12:38:00,095) [     INFO]: Running config, name=example
(2022-04-01 12:38:00,095) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 368.08 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed:  33%|███▎      | 1/3 [00:30<01:01, 30.61s/ chunks]Completed:  67%|██████▋   | 2/3 [00:30<00:12, 12.70s/ chunks]Completed: 100%|██████████| 3/3 [00:42<00:00, 12.31s/ chunks]Completed: 100%|██████████| 3/3 [00:42<00:00, 14.21s/ chunks]
(2022-04-01 12:38:42,728) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 399.29 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed: 100%|██████████| 3/3 [00:00<00:00, 237.49 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[5:inf])'
(2022-04-01 12:38:48,045) [     INFO]: Running config, name=example
(2022-04-01 12:38:48,045) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 409.13 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed:  33%|███▎      | 1/3 [00:31<01:02, 31.00s/ chunks]Completed: 100%|██████████| 3/3 [00:43<00:00, 12.49s/ chunks]Completed: 100%|██████████| 3/3 [00:43<00:00, 14.34s/ chunks]
(2022-04-01 12:39:31,092) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 352.35 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed: 100%|██████████| 3/3 [00:00<00:00, 244.50 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[6:inf])'
(2022-04-01 12:39:36,450) [     INFO]: Running config, name=example
(2022-04-01 12:39:36,450) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 404.67 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed:  33%|███▎      | 1/3 [00:32<01:04, 32.49s/ chunks]Completed:  67%|██████▋   | 2/3 [00:32<00:13, 13.50s/ chunks]Completed: 100%|██████████| 3/3 [00:45<00:00, 13.16s/ chunks]Completed: 100%|██████████| 3/3 [00:45<00:00, 15.15s/ chunks]
(2022-04-01 12:40:21,903) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 218.24 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed: 100%|██████████| 3/3 [00:00<00:00, 192.99 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[7:inf])'
(2022-04-01 12:40:27,380) [     INFO]: Running config, name=example
(2022-04-01 12:40:27,380) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 351.65 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed:  33%|███▎      | 1/3 [00:34<01:09, 34.65s/ chunks]Completed:  67%|██████▋   | 2/3 [00:35<00:14, 14.59s/ chunks]Completed: 100%|██████████| 3/3 [00:47<00:00, 13.74s/ chunks]Completed: 100%|██████████| 3/3 [00:47<00:00, 15.98s/ chunks]
(2022-04-01 12:41:15,320) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 376.20 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed: 100%|██████████| 3/3 [00:00<00:00, 177.47 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[8:inf])'
(2022-04-01 12:41:20,717) [     INFO]: Running config, name=example
(2022-04-01 12:41:20,717) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 388.84 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed:  33%|███▎      | 1/3 [00:35<01:11, 35.70s/ chunks]Completed:  67%|██████▋   | 2/3 [00:37<00:15, 15.84s/ chunks]Completed: 100%|██████████| 3/3 [00:50<00:00, 14.33s/ chunks]Completed: 100%|██████████| 3/3 [00:50<00:00, 16.73s/ chunks]
(2022-04-01 12:42:10,908) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 357.28 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed: 100%|██████████| 3/3 [00:00<00:00, 225.54 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[9:inf])'
(2022-04-01 12:42:16,451) [     INFO]: Running config, name=example
(2022-04-01 12:42:16,451) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 352.80 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed:  33%|███▎      | 1/3 [00:38<01:16, 38.15s/ chunks]Completed:  67%|██████▋   | 2/3 [00:38<00:15, 15.81s/ chunks]Completed: 100%|██████████| 3/3 [00:53<00:00, 15.59s/ chunks]Completed: 100%|██████████| 3/3 [00:53<00:00, 17.88s/ chunks]
(2022-04-01 12:43:10,109) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 341.97 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed: 100%|██████████| 3/3 [00:00<00:00, 214.33 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[10:inf])'
(2022-04-01 12:43:15,550) [     INFO]: Running config, name=example
(2022-04-01 12:43:15,550) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 385.13 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed:  33%|███▎      | 1/3 [00:43<01:27, 43.95s/ chunks]Completed:  67%|██████▋   | 2/3 [01:01<00:28, 28.40s/ chunks]Completed: 100%|██████████| 3/3 [01:15<00:00, 21.70s/ chunks]Completed: 100%|██████████| 3/3 [01:15<00:00, 25.07s/ chunks]
(2022-04-01 12:44:30,763) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 3 chunks [00:00, 359.52 chunks/s]
Completed:   0%|          | 0/3 [00:00<?, ? chunks/s]Completed: 100%|██████████| 3/3 [00:00<00:00, 217.36 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[11:inf])'
(2022-04-01 12:44:36,233) [     INFO]: Running config, name=example
(2022-04-01 12:44:36,234) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 253.65 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed:  50%|█████     | 1/2 [00:48<00:48, 48.63s/ chunks]Completed: 100%|██████████| 2/2 [01:05<00:00, 30.04s/ chunks]Completed: 100%|██████████| 2/2 [01:05<00:00, 32.83s/ chunks]
(2022-04-01 12:45:41,901) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 220.96 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed: 100%|██████████| 2/2 [00:00<00:00, 140.40 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[12:inf])'
(2022-04-01 12:45:47,373) [     INFO]: Running config, name=example
(2022-04-01 12:45:47,373) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 282.82 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed:  50%|█████     | 1/2 [00:56<00:56, 56.84s/ chunks]Completed: 100%|██████████| 2/2 [01:07<00:00, 29.81s/ chunks]Completed: 100%|██████████| 2/2 [01:07<00:00, 33.87s/ chunks]
(2022-04-01 12:46:55,115) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 252.69 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed: 100%|██████████| 2/2 [00:00<00:00, 142.70 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[13:inf])'
(2022-04-01 12:47:00,640) [     INFO]: Running config, name=example
(2022-04-01 12:47:00,640) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 285.61 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed:  50%|█████     | 1/2 [00:59<00:59, 59.07s/ chunks]Completed: 100%|██████████| 2/2 [02:48<00:00, 88.66s/ chunks]Completed: 100%|██████████| 2/2 [02:48<00:00, 84.22s/ chunks]
(2022-04-01 12:49:49,102) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 222.36 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed: 100%|██████████| 2/2 [00:00<00:00, 148.30 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[14:inf])'
(2022-04-01 12:49:54,612) [     INFO]: Running config, name=example
(2022-04-01 12:49:54,612) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 281.56 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed:  50%|█████     | 1/2 [01:31<01:31, 91.81s/ chunks]Completed: 100%|██████████| 2/2 [06:18<00:00, 206.32s/ chunks]Completed: 100%|██████████| 2/2 [06:18<00:00, 189.14s/ chunks]
(2022-04-01 12:56:12,912) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 242.31 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed: 100%|██████████| 2/2 [00:00<00:00, 159.79 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[15:inf])'
(2022-04-01 12:56:18,400) [     INFO]: Running config, name=example
(2022-04-01 12:56:18,400) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 257.96 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed:  50%|█████     | 1/2 [06:03<06:03, 363.41s/ chunks]Completed: 100%|██████████| 2/2 [06:18<00:00, 158.57s/ chunks]Completed: 100%|██████████| 2/2 [06:18<00:00, 189.30s/ chunks]
(2022-04-01 13:02:37,005) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 235.08 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed: 100%|██████████| 2/2 [00:00<00:00, 139.14 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[16:inf])'
(2022-04-01 13:02:42,588) [     INFO]: Running config, name=example
(2022-04-01 13:02:42,588) [     INFO]: Running phase, type=solver name=oracle
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 261.78 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed:  50%|█████     | 1/2 [56:10<56:10, 3370.70s/ chunks]Completed: 100%|██████████| 2/2 [1:12:41<00:00, 1970.74s/ chunks]Completed: 100%|██████████| 2/2 [1:12:41<00:00, 2180.73s/ chunks]
(2022-04-01 14:15:24,060) [     INFO]: Running phase, type=plotter name=plots
Submitted: 0 chunks [00:00, ? chunks/s]Submitted: 2 chunks [00:00, 216.35 chunks/s]
Completed:   0%|          | 0/2 [00:00<?, ? chunks/s]Completed: 100%|██████████| 2/2 [00:00<00:00, 147.27 chunks/s]
Traceback (most recent call last):
  File "generalized_learning.py", line 462, in <module>
    main(args)
  File "generalized_learning.py", line 439, in main
    config_manager.run(args)
  File "generalized_learning.py", line 422, in run
    results.append(config.execute())
  File "generalized_learning.py", line 340, in execute
    results.append(phase.execute())
  File "generalized_learning/plot/plot.py", line 447, in execute
    solutions_solved)
  File "generalized_learning/plot/plot.py", line 244, in _plot_bins
    solved_dict)
  File "generalized_learning/plot/plot.py", line 117, in get_bin_plots
    _y = solved_dict[solution_name].get_y(_x)
  File "generalized_learning/plot/series.py", line 36, in get_y
    return self._x[x]
KeyError: '(blocks:[51:inf])'
